version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pccc-postgres
    restart: always

    environment:
      POSTGRES_DB: pccc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Ho_Chi_Minh
      PGTZ: Asia/Ho_Chi_Minh

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pccc_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: